name: Jun's Note
description: Blog
meta_description: "My First Website, Note it"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://pjy5451.github.io"
google_analytics: "G-KF38MERZCL"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://pjy5451.github.io"
author: "Your Name"

# Disqus config
disqus-shortname: ""
