name: Jun's Note
description: Blog
meta_description: "My First Website, Note it"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "pjy5451.github.io"
domain_name: "http://yourblog-domain.com"
google_analytics: "G-KF38MERZCL"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Your Name"

# Disqus config
disqus-shortname: ""
